<?php

// ------------------------------------------------------------------------- //
//                           FreeContent for Xoops                           //
//                              Version:  3.x                                //
// ------------------------------------------------------------------------- //
// Author: Wang Jue (alias wjue)                                             //
// Purpose: Digest Headlines (WebDigest) from any webpage.                   //
//          wrap html or php-content into nice Xoops design.                 //
// email: wjue@wjue.org                                                      //
// URLs: http://www.wjue.org,  http://www.guanxiCRM.com                      //
//---------------------------------------------------------------------------//
//  This program is free software; you can redistribute it and/or modify     //
//  it under the terms of the GNU General Public License as published by     //
//  the Free Software Foundation; either version 2 of the License, or        //
//  (at your option) any later version.                                      //
//                                                                           //
//  This program is distributed in the hope that it will be useful,          //
//  but WITHOUT ANY WARRANTY; without even the implied warranty of           //
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            //
//  GNU General Public License for more details.                             //
//---------------------------------------------------------------------------//
//The compatibility Xoops wrapping method uses v1.0 of Stefan "SibSerag" Oese//

$modversion['name'] = _FC_MOD_NAME;
$modversion['version'] = '3.2';
$modversion['description'] = _FC_MOD_DESC;
$modversion['credits'] = 'WANG Jue';
$modversion['author'] = 'WANG Jue (wjue) http://www.wjue.org http://www.guanxiCRM.com ';
$modversion['help'] = 'help.html';
$modversion['license'] = 'GPL see LICENSE';
$modversion['official'] = 0;
$modversion['image'] = 'fc_logo.png';
$modversion['dirname'] = 'freecontent';

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = 'sql/mysql.sql';
//$modversion['sqlfile']['postgresql'] = "sql/pgsql.sql";

// Tables created by sql file (without prefix!)
$modversion['tables'][0] = 'freecontent';

// Menu
$modversion['hasMain'] = 1;
//$modversion['sub'][1]['name'] = 'WebDigest';
//$modversion['sub'][1]['url'] = "index.php?op=di";

// Templates
$modversion['templates'][1]['file'] = 'fc_index.html';
$modversion['templates'][1]['description'] = 'fc main template file';

$modversion['templates'][2]['file'] = 'fc_digest.html';
$modversion['templates'][2]['description'] = 'webdigest template file';

// Blocks
$modversion['blocks'][1]['file'] = 'freecontent.php';
$modversion['blocks'][1]['name'] = _FC_MOD_NAME;
$modversion['blocks'][1]['description'] = 'FreeContent Link Display';
$modversion['blocks'][1]['show_func'] = 'b_freecontent_show';
$modversion['blocks'][1]['template'] = 'freecontent_block.html';

$modversion['blocks'][2]['file'] = 'freecontent.php';
$modversion['blocks'][2]['name'] = _FC_MOD_MAGIC_NEWS;
$modversion['blocks'][2]['description'] = _FC_MOD_MAGIC_NEWS;
$modversion['blocks'][2]['show_func'] = 'b_freecontent_magicnews_show';
$modversion['blocks'][2]['template'] = 'freecontent_magicnews_block.html';

$modversion['blocks'][3]['file'] = 'freecontent.php';
$modversion['blocks'][3]['name'] = _FC_MOD_NEWSTICKER;
$modversion['blocks'][3]['description'] = 'Webdigest News Ticker';
$modversion['blocks'][3]['show_func'] = 'b_newsticker_show';
$modversion['blocks'][3]['template'] = 'freecontent_newsticker_block.html';
// Search
$modversion['hasSearch'] = 1;
$modversion['search']['file'] = 'include/search.inc.php';
$modversion['search']['func'] = 'freecontent_search';

// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = 'admin/index.php';
$modversion['adminmenu'] = 'admin/menu.php';

// Comments
$modversion['hasComments'] = 1;
$modversion['comments']['pageName'] = 'index.php';
$modversion['comments']['itemName'] = 'id';
